default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        name: Ensure conventional name on commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespaces
        files: \.(py|pyi)$

      - id: end-of-file-fixer
        name: Add empty new line at EOF
        files: \.(py|pyi)$

      - id: check-yaml
        name: Validate YAML syntax
        files: \.(yml|yaml)$

      - id: check-added-large-files
        name: Prevent large files from being committed

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check
        name: Run ruff (python linter)
        types: [python]

  - repo: local
    hooks:
      # Run unit test if python relevant file is modified (before commit)
      - id: pytest-unit
        name: Run unit tests
        entry: pytest tests/unit/
        language: system
        types: [python]
        stages: [pre-commit]

      # Run full test suite before pushing to remote
      - id: pytest-full
        name: Run full test suite
        entry: pytest tests/
        language: system
        types: [python]
        stages: [pre-push]
